db:
  image: mysql:latest
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: dev

redis:
  image: redis
  ports:
    - "6379:6379"

base: &base
  build: .
  volumes:
    - .:/myapp

sidekiq:
  <<: *base
  command: bundle exec sidekiq
  links:
    - db
    - redis

development: &dev_base
  <<: *base
  command: bundle exec rails s -p 4040 -b '0.0.0.0' -P tmp/pids/app.pid
  ports:
    - "4040:4040"
  environment:
    DATABASE_NAME: app_development
    RACK_ENV: development
    RAILS_ENV: development
  links:
    - db
    - redis

test:
  <<: *base
  ports: []
  command: bundle exec rspec
  environment:
    DATABASE_NAME: app_test
    RACK_ENV: test
    RAILS_ENV: test

bootstrap:
  <<: *base
  command: rails new . --force -d mysql
